"""
Report Generation Module
Generates comprehensive reconnaissance reports in TXT and PDF formats
"""

import html
import os
import json
from datetime import datetime
import logging
import config

# Set up logging
logger = logging.getLogger(__name__)


class Reporter:
    """Generates comprehensive reconnaissance reports"""
    
    def __init__(self, target, passive_results=None, active_results=None):
        self.target = target
        self.passive_results = passive_results or {}
        self.active_results = active_results or {}
        self.timestamp = datetime.now()
        self.report_dir = config.REPORTS_FOLDER
        
        # Create reports directory if it doesn't exist
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)
            logger.info(f"Created reports directory: {self.report_dir}")
    
    def generate_txt_report(self):
        """Generate a comprehensive text report"""
        timestamp_str = self.timestamp.strftime('%Y%m%d_%H%M%S')
        filename = f"{self.report_dir}/{self.target.replace('.', '_').replace(':', '_')}_{timestamp_str}.txt"
        
        logger.info(f"Generating TXT report: {filename}")
        
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                # Header
                f.write("="*80 + "\n")
                f.write(" " * 25 + "RECONNAISSANCE REPORT\n")
                f.write("="*80 + "\n\n")
                f.write(f"Target:        {self.target}\n")
                f.write(f"Report Date:   {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Generated By:  Recon Tool v2.0\n")
                f.write("="*80 + "\n\n")
                
                # Summary Statistics
                f.write("\n" + "="*80 + "\n")
                f.write("SUMMARY STATISTICS\n")
                f.write("="*80 + "\n\n")
                
                total_subdomains = len(self.passive_results.get('subdomains', []))
                total_open_ports = len(self.active_results.get('open_ports', []))
                total_banners = len(self.active_results.get('banners', {}))
                total_technologies = len(self.active_results.get('technologies', []))
                
                f.write(f"Subdomains Found:      {total_subdomains}\n")
                f.write(f"Open Ports Found:      {total_open_ports}\n")
                f.write(f"Banners Grabbed:       {total_banners}\n")
                f.write(f"Technologies Detected: {total_technologies}\n")
                f.write("\n")
                
                # Passive Reconnaissance
                if self.passive_results:
                    f.write("\n" + "="*80 + "\n")
                    f.write("PASSIVE RECONNAISSANCE\n")
                    f.write("="*80 + "\n")
                    
                    # WHOIS
                    if 'whois' in self.passive_results:
                        f.write("\n[WHOIS INFORMATION]\n")
                        f.write("-"*80 + "\n")
                        whois = self.passive_results['whois']
                        
                        if whois and 'error' not in whois:
                            f.write(f"Domain Name:      {whois.get('domain_name', 'N/A')}\n")
                            f.write(f"Organization:     {whois.get('org', 'N/A')}\n")
                            f.write(f"Registrar:        {whois.get('registrar', 'N/A')}\n")
                            f.write(f"Creation Date:    {whois.get('creation_date', 'N/A')}\n")
                            f.write(f"Expiration Date:  {whois.get('expiration_date', 'N/A')}\n")
                            f.write(f"Status:           {whois.get('status', 'N/A')}\n")
                            
                            if whois.get('name_servers'):
                                f.write(f"\nName Servers:\n")
                                for ns in whois['name_servers']:
                                    f.write(f"  → {ns}\n")
                            
                            if whois.get('emails'):
                                f.write(f"\nContact Emails:\n")
                                for email in whois['emails']:
                                    f.write(f"  → {email}\n")
                        elif whois and 'error' in whois:
                            f.write(f"Error: {whois['error']}\n")
                        else:
                            f.write("No WHOIS data available\n")
                        
                        f.write("\n")
                    
                    # DNS
                    if 'dns' in self.passive_results:
                        f.write("\n[DNS RECORDS]\n")
                        f.write("-"*80 + "\n")
                        
                        dns_data = self.passive_results['dns']
                        if dns_data:
                            for record_type in ['A', 'AAAA', 'MX', 'NS', 'TXT', 'SOA']:
                                if record_type in dns_data:
                                    records = dns_data[record_type]
                                    f.write(f"\n{record_type} Records:\n")
                                    if records:
                                        for record in records:
                                            f.write(f"  → {record}\n")
                                    else:
                                        f.write(f"  None found\n")
                        else:
                            f.write("No DNS data available\n")
                        
                        f.write("\n")
                    
                    # Subdomains
                    if 'subdomains' in self.passive_results:
                        f.write("\n[SUBDOMAINS]\n")
                        f.write("-"*80 + "\n")
                        subdomains = self.passive_results['subdomains']
                        f.write(f"Total Found: {len(subdomains)}\n\n")
                        
                        if subdomains:
                            for i, subdomain in enumerate(subdomains, 1):
                                f.write(f"{i:4d}. {subdomain}\n")
                        else:
                            f.write("  None found\n")
                        
                        f.write("\n")
                
                # Active Reconnaissance
                if self.active_results:
                    f.write("\n" + "="*80 + "\n")
                    f.write("ACTIVE RECONNAISSANCE\n")
                    f.write("="*80 + "\n")
                    
                    # IP Address and Scan Info
                    if 'ip_address' in self.active_results:
                        f.write("\n[SCAN INFORMATION]\n")
                        f.write("-"*80 + "\n")
                        f.write(f"IP Address:   {self.active_results['ip_address']}\n")
                        f.write(f"Scan Time:    {self.active_results.get('scan_time', 'N/A')}\n")
                        f.write("\n")
                    
                    # Port Scan
                    if 'open_ports' in self.active_results:
                        f.write("\n[PORT SCAN RESULTS]\n")
                        f.write("-"*80 + "\n")
                        open_ports = self.active_results['open_ports']
                        f.write(f"Total Open Ports: {len(open_ports)}\n\n")
                        
                        if open_ports:
                            # Header
                            f.write(f"{'Port':<10} {'State':<12} {'Service'}\n")
                            f.write("-"*80 + "\n")
                            
                            for port_info in open_ports:
                                if isinstance(port_info, dict):
                                    port = port_info.get('port', 'N/A')
                                    state = port_info.get('state', 'open')
                                    service = port_info.get('service', 'unknown')
                                else:
                                    port = port_info
                                    state = 'open'
                                    service = 'unknown'
                                
                                f.write(f"{str(port):<10} {state.upper():<12} {service}\n")
                        else:
                            f.write("  No open ports found\n")
                        
                        f.write("\n")
                    
                    # Banners
                    if 'banners' in self.active_results and self.active_results['banners']:
                        f.write("\n[BANNER GRABBING]\n")
                        f.write("-"*80 + "\n\n")
                        
                        for port, banner in self.active_results['banners'].items():
                            f.write(f"Port {port}:\n")
                            f.write("-" * 40 + "\n")
                            f.write(f"{banner}\n")
                            f.write("-" * 40 + "\n\n")
                    
                    # Technologies
                    if 'technologies' in self.active_results:
                        f.write("\n[TECHNOLOGY DETECTION]\n")
                        f.write("-"*80 + "\n")
                        technologies = self.active_results['technologies']
                        f.write(f"Total Technologies: {len(technologies)}\n\n")
                        
                        if technologies:
                            for i, tech in enumerate(technologies, 1):
                                f.write(f"{i:4d}. {tech}\n")
                        else:
                            f.write("  No technologies detected\n")
                        
                        f.write("\n")
                
                # Footer
                f.write("\n" + "="*80 + "\n")
                f.write("END OF REPORT\n")
                f.write("="*80 + "\n")
                f.write(f"Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write("Tool: Recon Tool v2.0\n")
                f.write("For Educational and Authorized Testing Purposes Only\n")
                f.write("="*80 + "\n")
            
            logger.info(f"TXT report generated successfully: {filename}")
            print(f"\n✅ TXT Report saved: {filename}")
            
            return filename
            
        except Exception as e:
            logger.error(f"Failed to generate TXT report: {str(e)}")
            print(f"❌ Error generating TXT report: {str(e)}")
            return None
    
    def generate_json_report(self):
        """Generate a JSON report for programmatic use"""
        timestamp_str = self.timestamp.strftime('%Y%m%d_%H%M%S')
        filename = f"{self.report_dir}/{self.target.replace('.', '_').replace(':', '_')}_{timestamp_str}.json"
        
        logger.info(f"Generating JSON report: {filename}")
        
        try:
            data = {
                'target': self.target,
                'timestamp': self.timestamp.isoformat(),
                'passive_reconnaissance': self.passive_results,
                'active_reconnaissance': self.active_results,
                'summary': {
                    'total_subdomains': len(self.passive_results.get('subdomains', [])),
                    'total_open_ports': len(self.active_results.get('open_ports', [])),
                    'total_banners': len(self.active_results.get('banners', {})),
                    'total_technologies': len(self.active_results.get('technologies', []))
                }
            }
            
            with open(filename, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, default=str)
            
            logger.info(f"JSON report generated successfully: {filename}")
            print(f"\n✅ JSON Report saved: {filename}")
            
            return filename
            
        except Exception as e:
            logger.error(f"Failed to generate JSON report: {str(e)}")
            print(f"❌ Error generating JSON report: {str(e)}")
            return None
    
    def generate_pdf_report(self):
        """Generate a PDF report (simplified version)"""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
            from reportlab.lib.enums import TA_CENTER
            from reportlab.lib import colors
        except ImportError:
            print("❌ ReportLab not installed. Install with: pip install reportlab")
            logger.error("ReportLab not available for PDF generation")
            return None
        
        timestamp_str = self.timestamp.strftime('%Y%m%d_%H%M%S')
        filename = f"{self.report_dir}/{self.target.replace('.', '_').replace(':', '_')}_{timestamp_str}.pdf"
        
        logger.info(f"Generating PDF report: {filename}")
        
        try:
            doc = SimpleDocTemplate(filename, pagesize=letter)
            elements = []
            styles = getSampleStyleSheet()
            
            # Custom title style
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#667eea'),
                spaceAfter=30,
                alignment=TA_CENTER
            )
            
            # Title
            elements.append(Spacer(1, 2*inch))
            elements.append(Paragraph("🔍 RECONNAISSANCE REPORT", title_style))
            elements.append(Spacer(1, 0.3*inch))
            elements.append(Paragraph(f"Target: {html.escape(self.target)}", styles['Normal']))
            elements.append(Paragraph(f"Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
            elements.append(PageBreak())
            
            # Summary
            elements.append(Paragraph("Summary Statistics", styles['Heading1']))
            summary_text = f"""
            Subdomains Found: {len(self.passive_results.get('subdomains', []))}<br/>
            Open Ports Found: {len(self.active_results.get('open_ports', []))}<br/>
            Banners Grabbed: {len(self.active_results.get('banners', {}))}<br/>
            Technologies Detected: {len(self.active_results.get('technologies', []))}
            """
            elements.append(Paragraph(summary_text, styles['Normal']))
            elements.append(Spacer(1, 0.5*inch))
            
            # Passive Recon (escape to prevent HTML/script injection in PDF viewer)
            if self.passive_results:
                elements.append(Paragraph("Passive Reconnaissance", styles['Heading1']))
                raw_text = html.escape(str(self.passive_results)[:1000])
                elements.append(Paragraph(raw_text, styles['Normal']))
                elements.append(Spacer(1, 0.3*inch))
            
            # Active Recon (escape to prevent HTML/script injection in PDF viewer)
            if self.active_results:
                elements.append(Paragraph("Active Reconnaissance", styles['Heading1']))
                raw_text = html.escape(str(self.active_results)[:1000])
                elements.append(Paragraph(raw_text, styles['Normal']))
            
            # Build PDF
            doc.build(elements)
            
            logger.info(f"PDF report generated successfully: {filename}")
            print(f"✅ PDF Report saved: {filename}")
            
            return filename
            
        except Exception as e:
            logger.error(f"Failed to generate PDF report: {str(e)}")
            print(f"❌ Error generating PDF report: {str(e)}")
            return None
    
    def generate_reports(self, format_type='txt'):
        """Generate report in specified format (txt, json, pdf)."""
        print(f"\n{'='*60}")
        print("📄 Generating Reports...")
        print(f"{'='*60}\n")
        
        if format_type == 'txt':
            return self.generate_txt_report()
        elif format_type == 'json':
            return self.generate_json_report()
        elif format_type == 'pdf':
            return self.generate_pdf_report()
        elif format_type == 'html':
            print("❌ HTML report is not yet implemented. Use --report txt, json, or pdf.")
            return None
        else:
            print(f"❌ Unknown report format: {format_type}")
            return None