"""
Report Generation Module 
Generates comprehensive reconnaissance reports in TXT and PDF formats, including all discovered data and verification results.
"""

import html
import os
import json
from datetime import datetime
import logging
import config

# Set up logging
logger = logging.getLogger(__name__)


class Reporter:
    """Generates comprehensive reconnaissance reports"""
    
    def __init__(self, target, passive_results=None, active_results=None):
        self.target = target
        self.passive_results = passive_results or {}
        self.active_results = active_results or {}
        self.timestamp = datetime.now()
        self.report_dir = config.REPORTS_FOLDER
        
        # Create reports directory if it doesn't exist
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)
            logger.info(f"Created reports directory: {self.report_dir}")
    
    def generate_txt_report(self):
        """Generate a comprehensive text report"""
        timestamp_str = self.timestamp.strftime('%Y%m%d_%H%M%S')
        filename = f"{self.report_dir}/{self.target.replace('.', '_').replace(':', '_')}_{timestamp_str}.txt"
        
        logger.info(f"Generating TXT report: {filename}")
        
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                # Header
                f.write("="*80 + "\n")
                f.write(" " * 25 + "RECONNAISSANCE REPORT\n")
                f.write("="*80 + "\n\n")
                f.write(f"Target:        {self.target}\n")
                f.write(f"Report Date:   {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"Generated By:  TEHQEEQ v1.0\n")
                f.write("="*80 + "\n\n")
                
                # Summary Statistics
                f.write("\n" + "="*80 + "\n")
                f.write("SUMMARY STATISTICS\n")
                f.write("="*80 + "\n\n")
                
                total_subdomains = len(self.passive_results.get('subdomains', []))
                total_verified_live = len(self.passive_results.get('verified_subdomains', {}).get('live', []))
                total_open_ports = len(self.active_results.get('open_ports', []))
                total_banners = len(self.active_results.get('banners', {}))
                total_technologies = len(self.active_results.get('technologies', []))
                
                f.write(f"Subdomains Found:         {total_subdomains}\n")
                if total_verified_live > 0:
                    f.write(f"Verified Live Subdomains: {total_verified_live}\n")
                f.write(f"Open Ports Found:         {total_open_ports}\n")
                f.write(f"Banners Grabbed:          {total_banners}\n")
                f.write(f"Technologies Detected:    {total_technologies}\n")
                f.write("\n")
                
                # Passive Reconnaissance
                if self.passive_results:
                    f.write("\n" + "="*80 + "\n")
                    f.write("PASSIVE RECONNAISSANCE\n")
                    f.write("="*80 + "\n")
                    
                    # WHOIS
                    if 'whois' in self.passive_results:
                        f.write("\n[WHOIS INFORMATION]\n")
                        f.write("-"*80 + "\n")
                        whois = self.passive_results['whois']
                        
                        if whois and 'error' not in whois:
                            f.write(f"Domain Name:      {whois.get('domain_name','Organization details not publicly available via PKNIC WHOIS')}\n")
                            f.write(f"Organization:     {whois.get('org', 'N/A')}\n")
                            f.write(f"Registrar:        {whois.get('registrar', 'N/A')}\n")
                            f.write(f"Creation Date:    {whois.get('creation_date', 'N/A')}\n")
                            f.write(f"Expiration Date:  {whois.get('expiration_date', 'N/A')}\n")
                            f.write(f"Status:           {whois.get('status', 'N/A')}\n")
                            
                            if whois.get('name_servers'):
                                f.write(f"\nName Servers:\n")
                                for ns in whois['name_servers']:
                                    f.write(f"  → {ns}\n")
                            
                            if whois.get('emails'):
                                f.write(f"\nContact Emails:\n")
                                for email in whois['emails']:
                                    f.write(f"  → {email}\n")
                        elif whois and 'error' in whois:
                            f.write(f"Error: {whois['error']}\n")
                        else:
                            f.write("No WHOIS data available\n")
                        
                        f.write("\n")
                    
                    # DNS
                    if 'dns' in self.passive_results:
                        f.write("\n[DNS RECORDS]\n")
                        f.write("-"*80 + "\n")
                        
                        dns_data = self.passive_results['dns']
                        if dns_data:
                            for record_type in ['A', 'AAAA', 'MX', 'NS', 'TXT', 'SOA']:
                                if record_type in dns_data:
                                    records = dns_data[record_type]
                                    f.write(f"\n{record_type} Records:\n")
                                    if records:
                                        # FIXED: Show ALL records, not just first few
                                        for record in records:
                                            f.write(f"  → {record}\n")
                                    else:
                                        f.write(f"  None found\n")
                        else:
                            f.write("No DNS data available\n")
                        
                        f.write("\n")
                    
                    # Subdomains - FIXED: Show ALL
                    if 'subdomains' in self.passive_results:
                        f.write("\n[SUBDOMAINS]\n")
                        f.write("-"*80 + "\n")
                        subdomains = self.passive_results['subdomains']
                        f.write(f"Total Found: {len(subdomains)}\n\n")
                        
                        if subdomains:
                            # FIXED: Show ALL subdomains, not just first 50
                            for i, subdomain in enumerate(subdomains, 1):
                                f.write(f"{i:4d}. {subdomain}\n")
                        else:
                            f.write("  None found\n")
                        
                        f.write("\n")
                    
                    # VERIFICATION SECTION - NEW
                    if 'verified_subdomains' in self.passive_results:
                        verified = self.passive_results['verified_subdomains']
                        
                        f.write("\n[SUBDOMAIN VERIFICATION]\n")
                        f.write("-"*80 + "\n")
                        f.write(f"Total Discovered:  {len(self.passive_results.get('subdomains', []))}\n")
                        f.write(f"Verified Live:     {len(verified.get('live', []))}\n")
                        f.write(f"Dead/Unreachable:  {len(verified.get('dead', []))}\n")
                        f.write(f"Internal Only:     {len(verified.get('internal', []))}\n\n")
                        
                        # Live subdomains with details
                        live_subs = verified.get('live', [])
                        if live_subs:
                            f.write("VERIFIED LIVE SUBDOMAINS:\n")
                            for i, item in enumerate(live_subs, 1):
                                subdomain = item['subdomain']
                                if 'ip_addresses' in item:
                                    # DNS verification
                                    ips = ', '.join(item['ip_addresses'])
                                    f.write(f"{i:4d}. {subdomain:<50} → {ips}\n")
                                else:
                                    # HTTP verification
                                    status = item.get('https_status') or item.get('http_status', 'N/A')
                                    f.write(f"{i:4d}. {subdomain:<50} [Status: {status}]\n")
                            f.write("\n")
                        
                        # Internal-only subdomains
                        internal_subs = verified.get('internal', [])
                        if internal_subs:
                            f.write("INTERNAL SUBDOMAINS (Private IPs):\n")
                            for i, item in enumerate(internal_subs, 1):
                                subdomain = item['subdomain']
                                ips = ', '.join(item.get('ip_addresses', []))
                                f.write(f"{i:4d}. {subdomain:<50} → {ips}\n")
                            f.write("\n")
                
                # Active Reconnaissance
                if self.active_results:
                    f.write("\n" + "="*80 + "\n")
                    f.write("ACTIVE RECONNAISSANCE\n")
                    f.write("="*80 + "\n")
                    
                    # IP Address and Scan Info
                    if 'ip_address' in self.active_results:
                        f.write("\n[SCAN INFORMATION]\n")
                        f.write("-"*80 + "\n")
                        f.write(f"IP Address:   {self.active_results['ip_address']}\n")
                        f.write(f"Scan Time:    {self.active_results.get('scan_time', 'N/A')}\n")
                        f.write("\n")
                    
                    # Port Scan
                    if 'open_ports' in self.active_results:
                        f.write("\n[PORT SCAN RESULTS]\n")
                        f.write("-"*80 + "\n")
                        open_ports = self.active_results['open_ports']
                        f.write(f"Total Open Ports: {len(open_ports)}\n\n")
                        
                        if open_ports:
                            # Header
                            f.write(f"{'Port':<10} {'State':<12} {'Service'}\n")
                            f.write("-"*80 + "\n")
                            
                            for port_info in open_ports:
                                if isinstance(port_info, dict):
                                    port = port_info.get('port', 'N/A')
                                    state = port_info.get('state', 'open')
                                    service = port_info.get('service', 'unknown')
                                else:
                                    port = port_info
                                    state = 'open'
                                    service = 'unknown'
                                
                                f.write(f"{str(port):<10} {state.upper():<12} {service}\n")
                        else:
                            f.write("  No open ports found\n")
                        
                        f.write("\n")
                    
                    # Banners
                    if 'banners' in self.active_results and self.active_results['banners']:
                        f.write("\n[BANNER GRABBING]\n")
                        f.write("-"*80 + "\n\n")
                        
                        for port, banner in self.active_results['banners'].items():
                            f.write(f"Port {port}:\n")
                            f.write("-" * 40 + "\n")
                            f.write(f"{banner}\n")
                            f.write("-" * 40 + "\n\n")
                    
                    # Technologies
                    if 'technologies' in self.active_results:
                        f.write("\n[TECHNOLOGY DETECTION]\n")
                        f.write("-"*80 + "\n")
                        technologies = self.active_results['technologies']
                        f.write(f"Total Technologies: {len(technologies)}\n\n")
                        
                        if technologies:
                            for i, tech in enumerate(technologies, 1):
                                f.write(f"{i:4d}. {tech}\n")
                        else:
                            f.write("  No technologies detected\n")
                        
                        f.write("\n")
                
                # Footer
                f.write("\n" + "="*80 + "\n")
                f.write("END OF REPORT\n")
                f.write("="*80 + "\n")
                f.write(f"Generated: {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write("Tool: TEHQEEQ v1.0\n")
                f.write("For Educational and Authorized Testing Purposes Only\n")
                f.write("="*80 + "\n")
            
            logger.info(f"TXT report generated successfully: {filename}")
            print(f"\n✅ TXT Report saved: {filename}")
            
            return filename
            
        except Exception as e:
            logger.error(f"Failed to generate TXT report: {str(e)}")
            print(f"❌ Error generating TXT report: {str(e)}")
            return None
    
    def generate_json_report(self):
        """Generate a JSON report for programmatic use"""
        timestamp_str = self.timestamp.strftime('%Y%m%d_%H%M%S')
        filename = f"{self.report_dir}/{self.target.replace('.', '_').replace(':', '_')}_{timestamp_str}.json"
        
        logger.info(f"Generating JSON report: {filename}")
        
        try:
            data = {
                'target': self.target,
                'timestamp': self.timestamp.isoformat(),
                'passive_reconnaissance': self.passive_results,
                'active_reconnaissance': self.active_results,
                'summary': {
                    'total_subdomains': len(self.passive_results.get('subdomains', [])),
                    'verified_live': len(self.passive_results.get('verified_subdomains', {}).get('live', [])),
                    'total_open_ports': len(self.active_results.get('open_ports', [])),
                    'total_banners': len(self.active_results.get('banners', {})),
                    'total_technologies': len(self.active_results.get('technologies', []))
                }
            }
            
            with open(filename, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, default=str)
            
            logger.info(f"JSON report generated successfully: {filename}")
            print(f"\n✅ JSON Report saved: {filename}")
            
            return filename
            
        except Exception as e:
            logger.error(f"Failed to generate JSON report: {str(e)}")
            print(f"❌ Error generating JSON report: {str(e)}")
            return None
    
    def _pdf_esc(self, s):
        """Escape text for ReportLab Paragraph (HTML-like)."""
        if s is None:
            return 'N/A'
        return html.escape(str(s))

    def generate_pdf_report(self):
        """Generate a well-formatted PDF report with ALL data and verification results."""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, PageBreak,
                Table, TableStyle,
            )
            from reportlab.lib.enums import TA_CENTER, TA_LEFT
            from reportlab.lib import colors
        except ImportError:
            print("❌ ReportLab not installed. Install with: pip install reportlab")
            logger.error("ReportLab not available for PDF generation")
            return None

        timestamp_str = self.timestamp.strftime('%Y%m%d_%H%M%S')
        filename = f"{self.report_dir}/{self.target.replace('.', '_').replace(':', '_')}_{timestamp_str}.pdf"

        logger.info(f"Generating PDF report: {filename}")

        try:
            doc = SimpleDocTemplate(
                filename, pagesize=letter,
                leftMargin=0.75*inch, rightMargin=0.75*inch,
                topMargin=0.75*inch, bottomMargin=0.75*inch,
            )
            elements = []
            styles = getSampleStyleSheet()

            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=22,
                textColor=colors.HexColor('#2563eb'),
                spaceAfter=12,
                alignment=TA_CENTER,
            )
            h1_style = ParagraphStyle(
                'ReportH1',
                parent=styles['Heading1'],
                fontSize=14,
                textColor=colors.HexColor('#1e40af'),
                spaceBefore=14,
                spaceAfter=8,
            )
            h2_style = ParagraphStyle(
                'ReportH2',
                parent=styles['Heading2'],
                fontSize=11,
                textColor=colors.HexColor('#374151'),
                spaceBefore=10,
                spaceAfter=4,
            )
            body_style = ParagraphStyle(
                'ReportBody',
                parent=styles['Normal'],
                fontSize=9,
                leading=11,
                spaceAfter=4,
            )
            small_style = ParagraphStyle(
                'ReportSmall',
                parent=styles['Normal'],
                fontSize=8,
                leading=10,
                leftIndent=12,
                spaceAfter=2,
            )

            # ----- Title -----
            elements.append(Spacer(1, 0.5*inch))
            elements.append(Paragraph("RECONNAISSANCE REPORT", title_style))
            elements.append(Paragraph(
                f"<b>Target:</b> {self._pdf_esc(self.target)}",
                body_style
            ))
            elements.append(Paragraph(
                f"<b>Generated:</b> {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
                body_style
            ))
            elements.append(Paragraph("TEHQEEQ v1.0 — For authorized security testing only.", small_style))
            elements.append(Spacer(1, 0.3*inch))

            # ----- Summary -----
            elements.append(Paragraph("1. Summary", h1_style))
            total_subs = len(self.passive_results.get('subdomains', []))
            total_verified = len(self.passive_results.get('verified_subdomains', {}).get('live', []))
            total_ports = len(self.active_results.get('open_ports', []))
            total_banners = len(self.active_results.get('banners', {}))
            total_techs = len(self.active_results.get('technologies', []))
            
            summary_data = [
                ['Metric', 'Count'],
                ['Subdomains found', str(total_subs)],
            ]
            if total_verified > 0:
                summary_data.append(['Verified live subdomains', str(total_verified)])
            summary_data.extend([
                ['Open ports found', str(total_ports)],
                ['Banners grabbed', str(total_banners)],
                ['Technologies detected', str(total_techs)],
            ])
            
            t = Table(summary_data, colWidths=[3*inch, 1.5*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e5e7eb')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('TOPPADDING', (0, 0), (-1, 0), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
            ]))
            elements.append(t)
            elements.append(Spacer(1, 0.35*inch))

            # ----- Passive Reconnaissance -----
            if self.passive_results:
                elements.append(Paragraph("2. Passive Reconnaissance", h1_style))

                # WHOIS
                if 'whois' in self.passive_results:
                    elements.append(Paragraph("2.1 WHOIS Information", h2_style))
                    whois = self.passive_results['whois']
                    if whois and 'error' not in whois:
                        whois_lines = [
                            f"<b>Domain:</b> {self._pdf_esc(whois.get('domain_name', 'N/A'))}",
                            f"<b>Organization:</b> {self._pdf_esc(whois.get('org', 'N/A'))}",
                            f"<b>Registrar:</b> {self._pdf_esc(whois.get('registrar', 'N/A'))}",
                            f"<b>Created:</b> {self._pdf_esc(whois.get('creation_date', 'N/A'))}",
                            f"<b>Expires:</b> {self._pdf_esc(whois.get('expiration_date', 'N/A'))}",
                        ]
                        status = whois.get('status', 'N/A')
                        if isinstance(status, list):
                            status = ', '.join(str(s) for s in status[:5])
                        whois_lines.append(f"<b>Status:</b> {self._pdf_esc(status)}")
                        for line in whois_lines:
                            elements.append(Paragraph(line, body_style))
                        if whois.get('name_servers'):
                            elements.append(Paragraph("<b>Name servers:</b>", body_style))
                            # FIXED: Show ALL name servers
                            for ns in whois['name_servers']:
                                elements.append(Paragraph(f"• {self._pdf_esc(ns)}", small_style))
                        if whois.get('emails'):
                            elements.append(Paragraph("<b>Contact emails:</b>", body_style))
                            for email in whois['emails']:
                                elements.append(Paragraph(f"• {self._pdf_esc(email)}", small_style))
                    elif whois and 'error' in whois:
                        elements.append(Paragraph(f"Error: {self._pdf_esc(whois.get('error', 'Unknown'))}", body_style))
                    else:
                        elements.append(Paragraph("No WHOIS data available.", body_style))
                    elements.append(Spacer(1, 0.2*inch))

                # DNS
                if 'dns' in self.passive_results:
                    elements.append(Paragraph("2.2 DNS Records", h2_style))
                    dns_data = self.passive_results['dns']
                    if dns_data:
                        for record_type in ['A', 'AAAA', 'MX', 'NS', 'TXT', 'SOA']:
                            if record_type not in dns_data:
                                continue
                            records = dns_data[record_type]
                            if not records:
                                elements.append(Paragraph(f"<b>{record_type}:</b> None found", small_style))
                            else:
                                elements.append(Paragraph(f"<b>{record_type} records:</b>", body_style))
                                # FIXED: Show ALL records, not just 10
                                for r in records:
                                    elements.append(Paragraph(f"• {self._pdf_esc(str(r)[:200])}", small_style))
                    else:
                        elements.append(Paragraph("No DNS data available.", body_style))
                    elements.append(Spacer(1, 0.2*inch))

                # Subdomains - MAIN LIST (show first 100, then continue in appendix)
                if 'subdomains' in self.passive_results:
                    elements.append(Paragraph("2.3 Subdomains Discovery", h2_style))
                    subdomains = self.passive_results['subdomains']
                    elements.append(Paragraph(f"<b>Total discovered:</b> {len(subdomains)}", body_style))
                    
                    if subdomains:
                        # Show first 100 in main section
                        display_count = min(100, len(subdomains))
                        elements.append(Paragraph(f"<b>Showing first {display_count} subdomains:</b>", body_style))
                        elements.append(Spacer(1, 0.1*inch))
                        
                        for i, sub in enumerate(subdomains[:display_count], 1):
                            elements.append(Paragraph(f"{i}. {self._pdf_esc(sub)}", small_style))
                        
                        if len(subdomains) > display_count:
                            elements.append(Spacer(1, 0.1*inch))
                            elements.append(Paragraph(
                                f"<i>See Appendix A for complete list of all {len(subdomains)} subdomains</i>",
                                small_style
                            ))
                    else:
                        elements.append(Paragraph("None found.", small_style))
                    elements.append(Spacer(1, 0.25*inch))
                
                # VERIFICATION SECTION - NEW
                if 'verified_subdomains' in self.passive_results:
                    verified = self.passive_results['verified_subdomains']
                    
                    elements.append(Paragraph("2.4 Subdomain Verification", h2_style))
                    
                    # Summary
                    verif_summary = [
                        f"<b>Total discovered:</b> {len(self.passive_results.get('subdomains', []))}",
                        f"<b>Verified live:</b> {len(verified.get('live', []))}",
                        f"<b>Dead/unreachable:</b> {len(verified.get('dead', []))}",
                        f"<b>Internal only:</b> {len(verified.get('internal', []))}"
                    ]
                    for line in verif_summary:
                        elements.append(Paragraph(line, body_style))
                    elements.append(Spacer(1, 0.15*inch))
                    
                    # Live subdomains (show first 50, rest in appendix)
                    live_subs = verified.get('live', [])
                    if live_subs:
                        elements.append(Paragraph("<b>Verified Live Subdomains:</b>", body_style))
                        display_live = min(50, len(live_subs))
                        
                        for i, item in enumerate(live_subs[:display_live], 1):
                            subdomain = item['subdomain']
                            if 'ip_addresses' in item:
                                ips = ', '.join(item['ip_addresses'])
                                elements.append(Paragraph(f"{i}. {self._pdf_esc(subdomain)} → {self._pdf_esc(ips)}", small_style))
                            else:
                                status = item.get('https_status') or item.get('http_status', 'N/A')
                                elements.append(Paragraph(f"{i}. {self._pdf_esc(subdomain)} [Status: {status}]", small_style))
                        
                        if len(live_subs) > display_live:
                            elements.append(Spacer(1, 0.1*inch))
                            elements.append(Paragraph(
                                f"<i>See Appendix B for complete list of all {len(live_subs)} verified subdomains</i>",
                                small_style
                            ))
                    
                    elements.append(Spacer(1, 0.25*inch))

            # ----- Active Reconnaissance -----
            if self.active_results:
                elements.append(Paragraph("3. Active Reconnaissance", h1_style))

                if self.active_results.get('ip_address'):
                    elements.append(Paragraph("3.1 Scan Information", h2_style))
                    elements.append(Paragraph(
                        f"<b>IP:</b> {self._pdf_esc(self.active_results['ip_address'])} | "
                        f"<b>Time:</b> {self.active_results.get('scan_time', 'N/A')}",
                        body_style
                    ))
                    elements.append(Spacer(1, 0.15*inch))

                if 'open_ports' in self.active_results:
                    elements.append(Paragraph("3.2 Open Ports", h2_style))
                    open_ports = self.active_results['open_ports']
                    if open_ports:
                        port_data = [['Port', 'State', 'Service']]
                        for po in open_ports:
                            if isinstance(po, dict):
                                port_data.append([
                                    str(po.get('port', '')),
                                    str(po.get('state', 'open')),
                                    str(po.get('service', 'unknown')),
                                ])
                            else:
                                port_data.append([str(po), 'open', '—'])
                        pt = Table(port_data, colWidths=[1*inch, 1*inch, 2.5*inch])
                        pt.setStyle(TableStyle([
                            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e5e7eb')),
                            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                            ('FONTSIZE', (0, 0), (-1, -1), 9),
                            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
                            ('TOPPADDING', (0, 0), (-1, 0), 6),
                            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#d1d5db')),
                            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')]),
                        ]))
                        elements.append(pt)
                    else:
                        elements.append(Paragraph("No open ports found.", body_style))
                    elements.append(Spacer(1, 0.2*inch))

                if self.active_results.get('banners'):
                    elements.append(Paragraph("3.3 Banners", h2_style))
                    for port, banner in self.active_results['banners'].items():
                        elements.append(Paragraph(f"<b>Port {port}</b>", body_style))
                        banner_esc = self._pdf_esc(banner[:500].replace('\n', '<br/>'))
                        elements.append(Paragraph(f'<font size="8">{banner_esc}</font>', small_style))
                        elements.append(Spacer(1, 0.1*inch))
                    elements.append(Spacer(1, 0.15*inch))

                if 'technologies' in self.active_results and self.active_results['technologies']:
                    elements.append(Paragraph("3.4 Technologies Detected", h2_style))
                    for tech in self.active_results['technologies']:
                        elements.append(Paragraph(f"• {self._pdf_esc(tech)}", small_style))

            # ----- APPENDIX SECTION -----
            # Appendix A: Complete Subdomain List
            subdomains = self.passive_results.get('subdomains', [])
            if len(subdomains) > 100:
                elements.append(PageBreak())
                elements.append(Paragraph("Appendix A: Complete Subdomain List", h1_style))
                elements.append(Paragraph(f"All {len(subdomains)} discovered subdomains:", body_style))
                elements.append(Spacer(1, 0.15*inch))
                
                for i, sub in enumerate(subdomains, 1):
                    elements.append(Paragraph(f"{i}. {self._pdf_esc(sub)}", small_style))
                    # Add page break every 150 items to prevent overly long pages
                    if i % 150 == 0 and i < len(subdomains):
                        elements.append(PageBreak())
                        elements.append(Paragraph(f"Appendix A (continued) - Subdomains {i+1} onwards:", body_style))
                        elements.append(Spacer(1, 0.1*inch))
            
            # Appendix B: Complete Verified Live List
            if 'verified_subdomains' in self.passive_results:
                live_subs = self.passive_results['verified_subdomains'].get('live', [])
                if len(live_subs) > 50:
                    elements.append(PageBreak())
                    elements.append(Paragraph("Appendix B: Complete Verified Live Subdomains", h1_style))
                    elements.append(Paragraph(f"All {len(live_subs)} verified live subdomains with details:", body_style))
                    elements.append(Spacer(1, 0.15*inch))
                    
                    for i, item in enumerate(live_subs, 1):
                        subdomain = item['subdomain']
                        if 'ip_addresses' in item:
                            ips = ', '.join(item['ip_addresses'])
                            elements.append(Paragraph(f"{i}. {self._pdf_esc(subdomain)} → {self._pdf_esc(ips)}", small_style))
                        else:
                            status = item.get('https_status') or item.get('http_status', 'N/A')
                            elements.append(Paragraph(f"{i}. {self._pdf_esc(subdomain)} [Status: {status}]", small_style))
                        
                        if i % 100 == 0 and i < len(live_subs):
                            elements.append(PageBreak())
                            elements.append(Paragraph(f"Appendix B (continued) - Verified subdomains {i+1} onwards:", body_style))
                            elements.append(Spacer(1, 0.1*inch))

            # Footer note
            elements.append(Spacer(1, 0.4*inch))
            elements.append(Paragraph(
                "— End of report. Generated by TEHQEEQ v1.0. For authorized use only.—",
                small_style
            ))

            doc.build(elements)

            logger.info(f"PDF report generated successfully: {filename}")
            print(f"✅ PDF Report saved: {filename}")

            return filename

        except Exception as e:
            logger.error(f"Failed to generate PDF report: {str(e)}")
            print(f"❌ Error generating PDF report: {str(e)}")
            import traceback
            traceback.print_exc()
            return None
    
    def generate_reports(self, format_type='txt'):
        """Generate report in specified format (txt, json, pdf)."""
        print(f"\n{'='*60}")
        print("📄 Generating Reports...")
        print(f"{'='*60}\n")
        
        if format_type == 'txt':
            return self.generate_txt_report()
        elif format_type == 'json':
            return self.generate_json_report()
        elif format_type == 'pdf':
            return self.generate_pdf_report()
        elif format_type == 'html':
            print("❌ HTML report is not yet implemented. Use --report txt, json, or pdf.")
            return None
        else:
            print(f"❌ Unknown report format: {format_type}")
            return None